/*
 * =====================================================================================
 *
 *
 *	Filename:  MsgDef.h
 *	Description:   
 *
 *	Version:  1.0
 *	Created: 2020/06/10
 *
 *	Author:  philip、cwb
 *	Organization:  ICHINAE(BEIJING) TECH.CO.,LTD. 
 *
 * =====================================================================================
*/

#ifndef __IOT_MSG_DEFINE_H__
#define __IOT_MSG_DEFINE_H__


// program name for each process
#define IOT_WEBACCESS				"iotuseracs"
#define IOT_DEVICEACCESS			"iotds"
#define IOT_CLIENTACCESS			"iotclientacs"
#define IOT_MYSQLSERVER				"iotrelationdb"
#define IOT_SEQUENCEDB				"iottimedb"
#define IOT_MODELSERVER				"iotdevmodel"
#define IOT_RULEENGINE				"iotrule"
#define IOT_AUTHSERVER				"iotauth"
#define IOT_VGATEWAY 				"iotvgateway"
#define IOT_LOCALDAEMON				"iotlocaldaemon"
#define IOT_LOCALMONITOR			"iotlocalmonitor"
#define IOT_DH_TRANS_PROGRAM 		"dev_dh_transmit_program"
// topic for process communication
#define IOT_AUTH_TOPIC            	"sys.auth"			// 鉴权服务订阅主题
#define IOT_RELATION_DB_TOPIC       "sys.relationdb"	// 关系数据库订阅主题
#define IOT_IOTM_TOPIC             	"sys.dev_mod"		// 物模型订阅主题
#define IOT_WATCH_DOG				"sys.watch_dog"		// 看门狗订阅主题
#define IOT_TIME_SEQ_TOPIC          "sys.time_seq"		// 时序数据库订阅主题
#define IOT_DEV_ACCESS_TOPIC        "sys.iotds"			// 接入服务订阅主题
#define IOT_RULE_TOPIC           	"sys.rule"			// 规则引擎订阅主题
#define IOT_TIMEDB_TOPIC           	"sys.timedb"		// 时序数据库订阅主题
#define IOT_TIMEDB_QUERY_TOPIC      "sys.timedb.query"	// 时序数据库查询主题
#define IOT_DEV_STAT_TOPIC			"sys.dev_stat"		// 设备状态订阅主题
#define IOT_CLIENT_ACCESS_TOPIC		"sys.access.client"

/**
 * message type enum value format:
 * 	MSG_IOT_{MODULE}_{ACTION}_{REQ|RSP}
 */
typedef enum EMsgType {
	MSG_IOT_COMMON_RSP								,
	/* for authenticate */
	MSG_IOT_AUTH_MSG = 10000						,
	MSG_IOT_AUTH_DEV								, // auth
	MSG_IOT_AUTH_DEV_RSP							, // auth
	MSG_IOT_AUTH_USER								, // auth
	MSG_IOT_AUTH_USER_RSP							, // auth
	MSG_IOT_AUTH_CLIENT								, // auth
	MSG_IOT_AUTH_CLIENT_RSP							, // auth
	MSG_IOT_AUTH_GW									, // gw auth
	MSG_IOT_AUTH_GW_RSP								, // gw auth rsp
	MSG_IOT_AUTH_REG                                , // user register
	MSG_IOT_AUTH_REG_RSP                            , // user register rsp
	MSG_IOT_AUTH_PRO                                , // product auth
	MSG_IOT_AUTH_PRO_RSP                            , // product auth rsp

	/* for device model */
	MSG_IOT_IOTM_MSG = 20000						,
	MSG_IOT_DEV_REQUEST_MODEL						, // 
	MSG_IOT_DEV_REQUEST_MODEL_RSP					,
	MSG_IOT_DEV_PUB_MODEL							, // Web
	MSG_IOT_DEV_PUB_MODEL_RSP						,
	MSG_IOT_DEV_UNPUB_MODEL							, // Web
	MSG_IOT_DEV_UNPUB_MODEL_RSP						,
	MSG_IOT_DEV_REMOVE_MODEL						, // Web
	MSG_IOT_DEV_REMOVE_MODEL_RSP					,
	MSG_IOT_DEV_GET_TOPIC 							,
	MSG_IOT_DEV_GET_TOPIC_RSP						,
	MSG_IOT_DEV_GET_SHADOW_INFO						, // Web
	MSG_IOT_DEV_GET_SERV_RESULT						,
	MSG_IOT_DEV_GET_SERV_RESULT_RSP					, // Web
	MSG_IOT_DEV_SET_PROPERTY						, // Web/GW
	MSG_IOT_DEV_SET_PROPERTY_RSP					, // Web
	MSG_IOT_DEV_GET_PROPERTY						, // Web/GW
	MSG_IOT_DEV_GET_PROPERTY_RSP					, // Web
	MSG_IOT_DEV_SET_SERVICE							, // Web/GW
	MSG_IOT_DEV_SET_SERVICE_RSP						, // Web

	MSG_IOT_DEV_ONLINE							    , // GW
	MSG_IOT_DEV_OFFLINE								, // GW
	MSG_IOT_DEV_GET_MULTI_PROPERTY					, // GW

	MSG_IOT_DEV_MANAGE								, // Web/GW
	MSG_IOT_DEV_ONLINE_INFO							, // Web
	MSG_IOT_DEV_ONLINE_INFO_RSP						, // Web

	/** for device config */
	MSG_IOT_DEV_GET_CONFIG 							, 
	MSG_IOT_DEV_GET_CONFIG_RSP						,
	/** device active stat */
	MSG_IOT_DEV_LAST_ACTIVE							,
	MSG_IOT_DEV_LAST_ACTIVE_RSP						,
	/** platform device statistics */
	MSG_IOT_DEV_STATISTICS							,
	MSG_IOT_DEV_STATISTICS_RSP						,
	MSG_IOT_DEV_ALERT 								,


	/* for rule engine */
	MSG_IOT_RULE_MSG = 30000						,
	MSG_IOT_RULE_REAL_DEV_INFO_SUB					,
	MSG_IOT_RULE_REAL_DEV_INFO_UN_SUB				,
	MSG_IOT_RULE_ENABLE								,
	MSG_IOT_RULE_DISABLE							,

	
	/* for time series db */
	MSG_IOT_TSDB_MSG = 40000						,
	MSG_IOT_TSDB_INSERT_EVENT						, // TimeDB
	MSG_IOT_TSDB_INSERT_PROPERTY_SETTING_RSP		, // TimeDB
	MSG_IOT_TSDB_INSERT_PROPERTY_GETTING_RSP		, // TimeDB
	MSG_IOT_TSDB_INSERT_SERVICE_SETTING_RSP			, // TimeDB
	MSG_IOT_TSDB_QUERY_BY_DEVICE					, // TimeDB
	MSG_IOT_TSDB_QUERY_BY_TOPIC						, // TimeDB
	MSG_IOT_TSDB_QUERY_PAGE_BY_TOPIC				, // TimeDB
	MSG_IOT_TSDB_QUERY_COUNT_BY_TOPIC				, // TimeDB
	MSG_IOT_TSDB_GET_TOGETHER				        , // 聚合分析
	MSG_IOT_TSDB_GET_FLOW				            , // 流量统计
	
	
	/* for virtual gateway(iotds) */
	MSG_IOT_IOTDS_MSG = 50000						,
	MSG_IOT_GW_REPORT_EVENT                         , // Rule
    MSG_IOT_GW_SET_PROPERTY_RSP                     , // Rule
    MSG_IOT_GW_GET_PROPERTY_RSP                     , // Rule
    MSG_IOT_GW_SET_SERVICE_RSP                      , // Rule
	MSG_IOT_GW_GET_INFO								,
	MSG_IOT_GW_CONFIG_DEV							,
	MSG_IOT_GW_DEV_LOGOUT							,
	MSG_IOT_GW_DEV_LOGIN                            ,
	MSG_IOT_GW_DEV_LOGOUT_RSP						,
	MSG_IOT_GW_DEV_LOGIN_RSP						,
	
	
	/* for relaitionDB */	
	MSG_IOT_RDB_ADD_COMPANY = 60000,		/*增加厂商*/
	MSG_IOT_RDB_ADD_COMPANY_RSP,	
	MSG_IOT_RDB_DEL_COMPANY,			/*删除厂商*/
	MSG_IOT_RDB_DEL_COMPANY_RSP,		
	MSG_IOT_RDB_UPDATE_COMPANY,			/*更新厂商*/
	MSG_IOT_RDB_UPDATE_COMPANY_RSP,		
	MSG_IOT_RDB_GET_COMPANY_NUM,		/*获取厂商数量*/
	MSG_IOT_RDB_GET_COMPANY_NUM_RSP,
	MSG_IOT_RDB_GET_COMPANY_LIST,		/*获取厂商列表*/
	MSG_IOT_RDB_GET_COMPANY_LIST_RSP,	
	MSG_IOT_RDB_GET_COMPANY_INFO,		/*获取指定查询的厂商*/
	MSG_IOT_RDB_GET_COMPANY_INFO_RSP,
	MSG_IOT_RDB_COMPANY_RELA_PRODUCT,	/*厂商关联产品*/
	MSG_IOT_RDB_COMPANY_RELA_PRODUCT_RSP,
	MSG_IOT_RDB_COMPANY_DISC_PRODUCT,	/*厂商断联产品*/
	MSG_IOT_RDB_COMPANY_DISC_PRODUCT_RSP,
	MSG_IOT_RDB_COMPANY_FIND_PRODUCT_BY_ID,/*厂商查找已关联产品*/
	MSG_IOT_RDB_COMPANY_FIND_PRODUCT_BY_ID_RSP,
	MSG_IOT_RDB_COMPANY_FIND_PRODUCT,	/*厂商查找未关联产品*/
	MSG_IOT_RDB_COMPANY_FIND_PRODUCT_RSP,
	MSG_IOT_RDB_ADD_PRO,				/*增加程序*/
	MSG_IOT_RDB_ADD_PRO_RSP,			
	MSG_IOT_RDB_DEL_PRO,				/*删除程序*/
	MSG_IOT_RDB_DEL_PRO_RSP,			
	MSG_IOT_RDB_UPDATE_PRO,				/*更新程序*/
	MSG_IOT_RDB_UPDATE_PRO_RSP,			
	MSG_IOT_RDB_GET_PRO_NUM,			/*获取程序数量*/
	MSG_IOT_RDB_GET_PRO_NUM_RSP,
	MSG_IOT_RDB_GET_PRO_LIST,			/*获取程序列表*/
	MSG_IOT_RDB_GET_PRO_LIST_RSP,		
	MSG_IOT_RDB_GET_PRO_QUERY,			/*获取指定查询的程序*/
	MSG_IOT_RDB_GET_PRO_QUERY_RSP,		
	MSG_IOT_RDB_ADD_DEVICE,				/*增加设备*/
	MSG_IOT_RDB_ADD_DEVICE_RSP,
	MSG_IOT_RDB_ADD_DEVICES,			/*批量增加设备*/
	MSG_IOT_RDB_ADD_DEVICES_RSP,		
	MSG_IOT_RDB_DEL_DEVICE,				/*删除设备*/
	MSG_IOT_RDB_DEL_DEVICE_RSP,			
	MSG_IOT_RDB_UPDATE_DEVICE,			/*更新设备*/
	MSG_IOT_RDB_UPDATE_DEVICE_RSP,
	MSG_IOT_RDB_GET_DEVICE_SUM,			/*获取设备总量*/
	MSG_IOT_RDB_GET_DEVICE_SUM_RSP,		
	MSG_IOT_RDB_GET_DEVICE_NUM,			/*获取模糊查询设备数量*/
	MSG_IOT_RDB_GET_DEVICE_NUM_RSP,		
	MSG_IOT_RDB_GET_DEVICE_LIST,		/*获取模糊查询的设备信息*/
	MSG_IOT_RDB_GET_DEVICE_LIST_RSP,
	MSG_IOT_RDB_CASE_GET_DEVICE_LIST,	/*分组获取设备列表*/
	MSG_IOT_RDB_CASE_GET_DEVICE_LIST_RSP,
	MSG_IOT_RDB_CONDITION_DEVICE_NUM,	/*条件查询设备数量*/
	MSG_IOT_RDB_CONDITION_DEVICE_NUM_RSP,
	MSG_IOT_RDB_CONDITION_DEVICE_LIST,	/*条件查询设备列表*/
	MSG_IOT_RDB_CONDITION_DEVICE_LIST_RSP,
	MSG_IOT_RDB_GET_DEVICE,				/*物模型获取设备列表*/
	MSG_IOT_RDB_GET_DEVICE_RSP,	
	MSG_IOT_RDB_GET_DEVICE_INFO,		/*获取指定查询单个设备的信息*/
	MSG_IOT_RDB_GET_DEVICE_INFO_RSP,		
	MSG_IOT_RDB_SET_DEVICE_STAT,		/*设置设备状态*/
	MSG_IOT_RDB_SET_DEVICE_STAT_RSP,
	MSG_IOT_RDB_SET_DEVICE_GIS,			/*设置设备经纬度信息*/
	MSG_IOT_RDB_SET_DEVICE_GIS_RSP,
	MSG_IOT_RDB_USER_LOGIN,				/*web端用户登录*/
	MSG_IOT_RDB_USER_LOGIN_RSP,
	MSG_IOT_RDB_USER_LOGOUT,			/*web端用户注销*/
	MSG_IOT_RDB_USER_LOGOUT_RSP,
	MSG_IOT_RDB_CREATE_USER,			/*创建web端用户*/
	MSG_IOT_RDB_CREATE_USER_RSP,
	MSG_IOT_RDB_MODIFY_USER_STATUS,		/*修改web端用户状态*/
	MSG_IOT_RDB_MODIFY_USER_STATUS_RSP,
	MSG_IOT_RDB_MODIFY_PASSWORD,		/*修改web端用户密码*/
	MSG_IOT_RDB_MODIFY_PASSWORD_RSP,
	MSG_IOT_RDB_PERMISSION_CHECK,		/*web用户权限校验*/
	MSG_IOT_RDB_PERMISSION_CHECK_RSP,
	MSG_IOT_RDB_DELETE_USER,			/*删除web端用户*/
	MSG_IOT_RDB_DELETE_USER_RSP,
	MSG_IOT_RDB_UPDATE_USER,			/*更新web端用户*/
	MSG_IOT_RDB_UPDATE_USER_RSP,
	MSG_IOT_RDB_GET_USER_NUM,			/*获取web用户数量*/
	MSG_IOT_RDB_GET_USER_NUM_RSP,
	MSG_IOT_RDB_GET_USER_LIST,			/*获取web用户列表*/
	MSG_IOT_RDB_GET_USER_LIST_RSP,
	MSG_IOT_RDB_QUERY_USER_INFO,		/*查询指定用户信息*/
	MSG_IOT_RDB_QUERY_USER_INFO_RSP,
	MSG_IOT_RDB_CREATE_ROLE,			/*创建角色*/
	MSG_IOT_RDB_CREATE_ROLE_RSP,
	MSG_IOT_RDB_DELETE_ROLE,			/*删除角色*/
	MSG_IOT_RDB_DELETE_ROLE_RSP,
	MSG_IOT_RDB_UPDATE_ROLE,			/*更新角色*/
	MSG_IOT_RDB_UPDATE_ROLE_RSP,
	MSG_IOT_RDB_QUERY_ROLE_INFO,		/*查询角色信息*/
	MSG_IOT_RDB_QUERY_ROLE_INFO_RSP,
	MSG_IOT_RDB_GET_ROLE_NUM,			/*查询角色数量*/
	MSG_IOT_RDB_GET_ROLE_NUM_RSP,
	MSG_IOT_RDB_GET_ROLE_LIST,			/*查询角色列表*/
	MSG_IOT_RDB_GET_ROLE_LIST_RSP,
	MSG_IOT_RDB_GET_PERMISSION_LIST,	/*查询权限列表*/
	MSG_IOT_RDB_GET_PERMISSION_LIST_RSP,
	MSG_IOT_RDB_GET_PRODUCT,			/*物模型数据获取产品列表*/
	MSG_IOT_RDB_GET_PRODUCT_RSP,		
	MSG_IOT_RDB_ADD_PRODUCT,			/*增加产品*/
	MSG_IOT_RDB_ADD_PRODUCT_RSP,
	MSG_IOT_RDB_DEL_PRODUCT,			/*删除产品*/
	MSG_IOT_RDB_DEL_PRODUCT_RSP,
	MSG_IOT_RDB_UPDATE_PRODUCT,			/*更新产品*/
	MSG_IOT_RDB_UPDATE_PRODUCT_RSP,
	MSG_IOT_RDB_GET_PUBLIC_PRODUCT,		/*获取公有产品*/
	MSG_IOT_RDB_GET_PUBLIC_PRODUCT_RSP,
	MSG_IOT_RDB_GET_PRIVATE_PRODUCT,	/*获取私有产品*/
	MSG_IOT_RDB_GET_PRIVATE_PRODUCT_RSP,	
	MSG_IOT_RDB_GET_PRODUCT_NUM,		/*获取产品数量*/
	MSG_IOT_RDB_GET_PRODUCT_NUM_RSP,
	MSG_IOT_RDB_GET_PRODUCT_LIST,		/*获取产品列表*/
	MSG_IOT_RDB_GET_PRODUCT_LIST_RSP,
	MSG_IOT_RDB_GET_PRODUCT_INFO,		/*获取产品信息*/
	MSG_IOT_RDB_GET_PRODUCT_INFO_RSP,
	MSG_IOT_RDB_GET_ID_BY_PRODUCTKEY,	/*获取产品id*/
	MSG_IOT_RDB_GET_ID_BY_PRODUCTKEY_RSP,
	MSG_IOT_RDB_ADD_LABEL,				/*添加标签*/
	MSG_IOT_RDB_ADD_LABEL_RSP,
	MSG_IOT_RDB_DELETE_LABEL,			/*删除标签*/
	MSG_IOT_RDB_DELETE_LABEL_RSP,
	MSG_IOT_RDB_MODIFY_LABEL,			/*修改标签*/
	MSG_IOT_RDB_MODIFY_LABEL_RSP,
	MSG_IOT_RDB_QUERY_LABEL_INFO,		/*查询标签信息*/
	MSG_IOT_RDB_QUERY_LABEL_INFO_RSP,
	MSG_IOT_RDB_QUERY_LABEL_PRODUCT_NUM,/*查询标签产品数量*/
	MSG_IOT_RDB_QUERY_LABEL_PRODUCT_NUM_RSP,
	MSG_IOT_RDB_QUERY_LABEL_PRODUCT_LIST,/*查询标签产品列表*/
	MSG_IOT_RDB_QUERY_LABEL_PRODUCT_LIST_RSP,
	MSG_IOT_RDB_GET_MODEL,				/*物模型服务获取物模型数据*/
	MSG_IOT_RDB_GET_MODEL_RSP,
	MSG_IOT_RDB_CREATE_MODEL,			/*创建物模型*/
	MSG_IOT_RDB_CREATE_MODEL_RSP,
	MSG_IOT_RDB_MODIFY_MODEL,			/*修改物模型*/
	MSG_IOT_RDB_MODIFY_MODEL_RSP,
	MSG_IOT_RDB_DELETE_MODEL,			/*删除物模型*/
	MSG_IOT_RDB_DELETE_MODEL_RSP,
	MSG_IOT_RDB_ADD_MODEL_SINGLE,		/*新增物模型单个指标*/
	MSG_IOT_RDB_ADD_MODEL_SINGLE_RSP,
	MSG_IOT_RDB_QUERY_MODEL_INFO,			/*查询物模型信息*/
	MSG_IOT_RDB_QUERY_MODEL_INFO_RSP,
	MSG_IOT_RDB_SET_MODEL_STATUS,		/*修改物模型状态*/
	MSG_IOT_RDB_SET_MODEL_STATUS_RSP,
	MSG_IOT_RDB_ADD_RULES,				/*添加规则*/
	MSG_IOT_RDB_ADD_RULES_RSP,
	MSG_IOT_RDB_DELETE_RULES,			/*删除规则*/
	MSG_IOT_RDB_DELETE_RULES_RSP,
	MSG_IOT_RDB_MODIFY_RULES,			/*修改规则*/
	MSG_IOT_RDB_MODIFY_RULES_RSP,
	MSG_IOT_RDB_SET_RULES_STATUS,		/*启用/禁用规则*/
	MSG_IOT_RDB_SET_RULES_STATUS_RSP,
	MSG_IOT_RDB_CONFIG_RULES,			/*配置规则*/
	MSG_IOT_RDB_CONFIG_RULES_RSP,
	MSG_IOT_RDB_UNCONFIG_RULES,			/*移除规则*/
	MSG_IOT_RDB_UNCONFIG_RULES_RSP,
	MSG_IOT_RDB_QUERY_CONFIG_INFO,		/*查询规则配置信息*/
	MSG_IOT_RDB_QUERY_CONFIG_INFO_RSP,
	MSG_IOT_RDB_QUERY_RULE_INFO,		/*查询规则信息*/
	MSG_IOT_RDB_QUERY_RULE_INFO_RSP,
	MSG_IOT_RDB_QUERY_CONFIG_NUM,		/*查询规则配置数量*/
	MSG_IOT_RDB_QUERY_CONFIG_NUM_RSP,
	MSG_IOT_RDB_QUERY_RULE_NUM,			/*查询规则数量*/
	MSG_IOT_RDB_QUERY_RULE_NUM_RSP,
	MSG_IOT_RDB_QUERY_CONFIG_LIST,		/*查询规则配置列表*/
	MSG_IOT_RDB_QUERY_CONFIG_LIST_RSP,
	MSG_IOT_RDB_QUERY_RULE_LIST,		/*查询规则列表*/
	MSG_IOT_RDB_QUERY_RULE_LIST_RSP,
	MSG_IOT_RDB_RULE_GET_PK,			/*规则获取PK*/
	MSG_IOT_RDB_RULE_GET_PK_RSP,
	MSG_IOT_RDB_RULE_GET_SN_AND_IDENT,	/*规则获取SN和Identifier*/
	MSG_IOT_RDB_RULE_GET_SN_AND_IDENT_RSP,
	MSG_IOT_RDB_RULE_GET_OUTPUT_IDENT,	/*规则获取事件输出的identifier*/
	MSG_IOT_RDB_RULE_GET_OUTPUT_IDENT_RSP,
	MSG_IOT_RDB_GET_ENABLE_RULE_ID,		/*获取已启用的规则*/
	MSG_IOT_RDB_GET_ENABLE_RULE_ID_RSP,
	MSG_IOT_RDB_ADD_MENU,				/*添加菜单*/
	MSG_IOT_RDB_ADD_MENU_RSP,
	MSG_IOT_RDB_DELETE_MENU,			/*删除菜单*/
	MSG_IOT_RDB_DELETE_MENU_RSP,
	MSG_IOT_RDB_MODIFY_MENU,			/*修改菜单*/
	MSG_IOT_RDB_MODIFY_MENU_RSP,
	MSG_IOT_RDB_QUERY_MENU_NUM,			/*查询菜单数量*/
	MSG_IOT_RDB_QUERY_MENU_NUM_RSP,
	MSG_IOT_RDB_QUERY_MENU_LIST,		/*查询菜单列表*/
	MSG_IOT_RDB_QUERY_MENU_LIST_RSP,
	MSG_IOT_RDB_ADD_PLUGIN,				/*添加插件*/
	MSG_IOT_RDB_ADD_PLUGIN_RSP,
	MSG_IOT_RDB_MODIFY_PLUGIN,			/*修改插件*/
	MSG_IOT_RDB_MODIFY_PLUGIN_RSP,
	MSG_IOT_RDB_DELETE_PLUGIN,			/*删除插件*/
	MSG_IOT_RDB_DELETE_PLUGIN_RSP,
	MSG_IOT_RDB_QUERY_PLUGIN,			/*查询插件*/
	MSG_IOT_RDB_QUERY_PLUGIN_RSP,
	MSG_IOT_RDB_QUERY_PLUGIN_NUM,		/*查询插件数量*/
	MSG_IOT_RDB_QUERY_PLUGIN_NUM_RSP,
	MSG_IOT_RDB_QUERY_PLUGIN_LIST,		/*查询插件列表*/
	MSG_IOT_RDB_QUERY_PLUGIN_LIST_RSP,
	MSG_IOT_RDB_LOAD_PLUGIN,			/*装载插件*/
	MSG_IOT_RDB_LOAD_PLUGIN_RSP,
	MSG_IOT_RDB_CREATE_CASE,			/*创建场景*/
	MSG_IOT_RDB_CREATE_CASE_RSP,
	MSG_IOT_RDB_DELETE_CASE,			/*删除场景*/
	MSG_IOT_RDB_DELETE_CASE_RSP,
	MSG_IOT_RDB_MODIFY_CASE,			/*修改场景*/
	MSG_IOT_RDB_MODIFY_CASE_RSP,
	MSG_IOT_RDB_QUERY_CASE_INFO,		/*查询场景信息*/
	MSG_IOT_RDB_QUERY_CASE_INFO_RSP,
	MSG_IOT_RDB_CASE_ADD_GROUP,			/*场景添加分组*/
	MSG_IOT_RDB_CASE_ADD_GROUP_RSP,
	MSG_IOT_RDB_CASE_DELETE_GROUP,		/*场景删除分组*/
	MSG_IOT_RDB_CASE_DELETE_GROUP_RSP,
	MSG_IOT_RDB_QUERY_GROUP_INFO,		/*获取场景分组信息*/
	MSG_IOT_RDB_QUERY_GROUP_INFO_RSP,
	MSG_IOT_RDB_CASE_MODIFY_GROUP,		/*场景修改分组*/
	MSG_IOT_RDB_CASE_MODIFY_GROUP_RSP,
	MSG_IOT_RDB_CASE_ADD_DEVICE,		/*场景添加设备*/
	MSG_IOT_RDB_CASE_ADD_DEVICE_RSP,
	MSG_IOT_RDB_CASE_DEL_DEVICE,		/*场景删除设备*/
	MSG_IOT_RDB_CASE_DEL_DEVICE_RSP,
	MSG_IOT_RDB_QUERY_CASE_NUM,			/*查询场景数量*/
	MSG_IOT_RDB_QUERY_CASE_NUM_RSP,
	MSG_IOT_RDB_QUERY_CASE_LIST,		/*查询场景列表*/
	MSG_IOT_RDB_QUERY_CASE_LIST_RSP,
	MSG_IOT_RDB_QUERY_GROUP_NUM,		/*查询分组数量*/
	MSG_IOT_RDB_QUERY_GROUP_NUM_RSP,
	MSG_IOT_RDB_QUERY_GROUP_LIST,		/*查询分组列表*/
	MSG_IOT_RDB_QUERY_GROUP_LIST_RSP,
	MSG_IOT_RDB_QUERY_CASE_DEV_LIST,	/*查询场景设备列表*/
	MSG_IOT_RDB_QUERY_CASE_DEV_LIST_RSP,
	MSG_IOT_RDB_QUERY_CASE_DEV_NUM,		/*查询场景设备数量*/
	MSG_IOT_RDB_QUERY_CASE_DEV_NUM_RSP,	
	MSG_IOT_RDB_QUERY_WARNING_CASE_LIST,/*查询异常设备列表*/
	MSG_IOT_RDB_QUERY_WARNING_CASE_LIST_RSP,
	MSG_IOT_RDB_QUERY_WARNING_CASE_NUM,	/*查询异常设备数量*/
	MSG_IOT_RDB_QUERY_WARNING_CASE_NUM_RSP,
	MSG_IOT_RDB_ADD_LOG,				/*添加日志*/
	MSG_IOT_RDB_ADD_LOG_RSP,
	MSG_IOT_RDB_QUERY_LOG_LIST,			/*获取日志列表*/
	MSG_IOT_RDB_QUERY_LOG_LIST_RSP,
	MSG_IOT_RDB_QUERY_LOG_NUM,			/*获取日志数量*/
	MSG_IOT_RDB_QUERY_LOG_NUM_RSP,
	MSG_IOT_RDB_DELETE_LOG,				/*删除日志*/
	MSG_IOT_RDB_DELETE_LOG_RSP,
	MSG_IOT_RDB_TIMING_DELETE_LOG,		/*定时删除日志*/
	MSG_IOT_RDB_TIMING_DELETE_LOG_RSP,
	MSG_IOT_RDB_ADD_GATEWAYSERVE,		/*添加网关服务*/
	MSG_IOT_RDB_ADD_GATEWAYSERVE_RSP,
	MSG_IOT_RDB_MODIFY_GATEWAYSERVE,	/*修改网关服务*/
	MSG_IOT_RDB_MODIFY_GATEWAYSERVE_RSP,
	MSG_IOT_RDB_DELETE_GATEWAYSERVE,	/*删除网关服务*/
	MSG_IOT_RDB_DELETE_GATEWAYSERVE_RSP,
	MSG_IOT_RDB_QUERY_GATEWAYSERVE,		/*查询网关服务*/
	MSG_IOT_RDB_QUERY_GATEWAYSERVE_RSP,
	MSG_IOT_RDB_QUERY_GATEWAYSERVE_NUM,	/*查询网关服务数量*/
	MSG_IOT_RDB_QUERY_GATEWAYSERVE_NUM_RSP,
	MSG_IOT_RDB_QUERY_GATEWAYSERVE_LIST,/*查询网关服务列表*/
	MSG_IOT_RDB_QUERY_GATEWAYSERVE_LIST_RSP,
	MSG_IOT_RDB_ENABLE_GATEWAYSERVE,	/*启用网关服务*/
	MSG_IOT_RDB_ENABLE_GATEWAYSERVE_RSP,
	MSG_IOT_RDB_GET_CLIENT_TOPIC,
	MSG_IOT_RDB_GET_CLIENT_TOPIC_RSP,
	MSG_IOT_RDB_ALERT_DEV_NUM,			/*告警设备数量*/
	MSG_IOT_RDB_ALERT_DEV_NUM_RSP,
	MSG_IOT_RDB_ALERT_DEV_LIST,			/*告警设备列表*/
	MSG_IOT_RDB_ALERT_DEV_LIST_RSP,

	MSG_IOT_RDB_DEVICE_AUTH_DATA					,
	MSG_IOT_RDB_DEVICE_AUTH_DATA_RSP				,

	/* for client access */	
	MSG_IOT_CLIENT_MSG = 70000						,
	MSG_IOT_CLIENT_REAL_DEV_REPORT_SUB				,
	
	/* for watchdog */
	MSG_IOT_WD_MSG = 80000							,
	MSG_IOT_WD_GET_ALL_RESOURCE						, // 获取所有硬件信息

	/* for device gateway*/
	MSG_IOT_GATEWAY_GET_CFG_LIST_REQ  = 90000		,
	MSG_IOT_GATEWAY_GET_CFG_LIST_RSP				,
} E_XIPC_MESSAGE;

#endif
